<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format2.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="2">
  <name>abb_resources</name>
  <version>1.5.0</version>
  <description>
    <p>
      Shared configuration data for ABB manipulators.
    </p>
    <p>
      This package contains common urdf / xacro resources used by
      ABB related packages.
    </p>
  </description>
  <author>Levi Armstrong (SwRI)</author>
  <maintainer email="noreply@rosindustrial.org">ROS-Industrial community</maintainer>
  <license>Apache-2.0</license>

  <url type="bugtracker">https://github.com/ros-industrial/abb/issues</url>
  <url type="repository">https://github.com/ros-industrial/abb</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <architecture_independent/>
    <build_type>ament_cmake</build_type>
    <rosindex>
      <tags>
        <tag>urdf</tag>
        <tag>xacro</tag>
        <tag>colour</tag>
        <tag>material</tag>
        <tag>mesh</tag>
        <tag>resources</tag>
        <tag>abb</tag>
        <tag>industrial</tag>
        <tag>ros-industrial</tag>
      </tags>
    </rosindex>
    <ros_industrial>
      <support_level value="community" />
    </ros_industrial>
  </export>
</package>
