set(_CATKIN_CURRENT_PACKAGE "abb_irb4400_moveit_config")
set(abb_irb4400_moveit_config_MAINTAINER "MoveIt Setup Assistant <assistant@moveit.ros.org>")
set(abb_irb4400_moveit_config_DEPRECATED "")
set(abb_irb4400_moveit_config_VERSION "0.2.0")
set(abb_irb4400_moveit_config_BUILD_DEPENDS "abb_irb4400_support")
set(abb_irb4400_moveit_config_RUN_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "abb_irb4400_support")
set(abb_irb4400_moveit_config_BUILDTOOL_DEPENDS "catkin")