joint_limits:
  joint_2:
    has_velocity_limits: true
    max_velocity: 1.5707
    has_acceleration_limits: true
    max_acceleration: 0.31414
  joint_6:
    has_velocity_limits: true
    max_velocity: 3.3161
    has_acceleration_limits: true
    max_acceleration: 0.66322
  joint_1:
    has_velocity_limits: true
    max_velocity: 1.7453
    has_acceleration_limits: true
    max_acceleration: 0.34906
  joint_5:
    has_velocity_limits: true
    max_velocity: 2.4435
    has_acceleration_limits: true
    max_acceleration: 0.4887
  joint_3:
    has_velocity_limits: true
    max_velocity: 1.5707
    has_acceleration_limits: true
    max_acceleration: 0.31414
  joint_4:
    has_velocity_limits: true
    max_velocity: 2.9671
    has_acceleration_limits: true
    max_acceleration: 0.59342